/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivosTable: typeof import('./src/components/ActivosTable.vue')['default']
    copy: typeof import('./src/components/responsablesTable copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    ResponsablesTable: typeof import('./src/components/ResponsablesTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UbicacionesTable: typeof import('./src/components/UbicacionesTable.vue')['default']
  }
}
